<a href="https://colab.research.google.com/github/itsmuza/ai_foundation/blob/main/studentsPerformance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [38]:
df = pd.read_csv("student_performance.csv")

In [39]:
print("dataset shape:", df.shape)

dataset shape: (1000000, 6)

In [40]:
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A

In [41]:
print("dataset columns:", df.columns.tolist())

dataset columns: ['student_id', 'weekly_self_study_hours', 'attendance_percentage', 'class_participation', 'total_score', 'grade']

In [42]:
df.describe()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,500000.500000,15.029127,84.711046,5.985203,84.283845
std,288675.278933,6.899431,9.424143,1.956421,15.432969
min,1.000000,0.000000,50.000000,0.000000,9.400000
25%,250000.750000,10.300000,78.300000,4.700000,73.900000
50%,500000.500000,15.000000,85.000000,6.000000,87.500000
75%,750000.250000,19.700000,91.800000,7.300000,100.000000
max,1000000.000000,40.000000,100.000000,10.000000,100.000000

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 6 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   student_id               1000000 non-null  int64
 1   weekly_self_study_hours  1000000 non-null  float64
 2   attendance_percentage    1000000 non-null  float64
 3   class_participation      1000000 non-null  float64
 4   total_score              1000000 non-null  float64
 5   grade                    1000000 non-null  object
dtypes: float64(4), int64(1), object(1)
memory usage: 45.8+ MB

In [44]:
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A

In [51]:
df_columns = df[['weekly_self_study_hours', 'attendance_percentage', 'class_participation', 'total_score']]
print(df_columns.mean())

weekly_self_study_hours    15.029127
attendance_percentage      84.711046
class_participation         5.985203
total_score                84.283845
dtype: float64

In [52]:
df_columns.min()

weekly_self_study_hours     0.0
attendance_percentage      50.0
class_participation         0.0
total_score                 9.4
dtype: float64

In [53]:
df_columns.max()

weekly_self_study_hours     40.0
attendance_percentage      100.0
class_participation         10.0
total_score                100.0
dtype: float64

In [54]:
df_columns.corr()

,weekly_self_study_hours,attendance_percentage,class_participation,total_score
weekly_self_study_hours,1.000000,-0.001008,0.001244,0.812241
attendance_percentage,-0.001008,1.000000,-0.000043,-0.001014
class_participation,0.001244,-0.000043,1.000000,0.000684
total_score,0.812241,-0.001014,0.000684,1.000000

In [58]:
df_columns

,weekly_self_study_hours,attendance_percentage,class_participation,total_score
0,18.5,95.6,3.8,97.9
1,14.0,80.0,2.5,83.9
2,19.5,86.3,5.3,100.0
3,25.7,70.2,7.0,100.0
4,13.4,81.9,6.9,92.0
...,...,...,...,...
999995,18.0,95.5,4.8,100.0
999996,15.7,82.7,6.7,88.3
999997,14.2,85.1,5.8,87.9
999998,25.3,90.0,5.3,100.0
999999,18.3,84.6,4.1,100.0

In [61]:
df['total_score']

0          97.9
1          83.9
2         100.0
3         100.0
4          92.0
          ...
999995    100.0
999996     88.3
999997     87.9
999998    100.0
999999    100.0
Name: total_score, Length: 1000000, dtype: float64

In [64]:
df['passed'] = np.where(df['total_score'] > 90, True, False)

In [65]:
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,passed
0,1,18.5,95.6,3.8,97.9,A,True
1,2,14.0,80.0,2.5,83.9,B,False
2,3,19.5,86.3,5.3,100.0,A,True
3,4,25.7,70.2,7.0,100.0,A,True
4,5,13.4,81.9,6.9,92.0,A,True
...,...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A,True
999996,999997,15.7,82.7,6.7,88.3,A,False
999997,999998,14.2,85.1,5.8,87.9,A,False
999998,999999,25.3,90.0,5.3,100.0,A,True
999999,1000000,18.3,84.6,4.1,100.0,A,True

In [78]:
df.groupby('grade')['weekly_self_study_hours'].mean()

grade
A    19.375738
B    12.115533
C     7.691161
D     3.764143
F     1.524662
Name: weekly_self_study_hours, dtype: float64

In [82]:
df['passed'].value_counts()

passed
False    550574
True     449426
Name: count, dtype: int64

In [95]:
values = df_columns.values
print(values)

print(np.mean(values, axis=0))
print(np.std(values, axis=0))

z_values =( values - np.mean(values, axis=0)) / np.std(values, axis=0)
print(z_values)

[[ 18.5  95.6   3.8  97.9]
 [ 14.   80.    2.5  83.9]
 [ 19.5  86.3   5.3 100. ]
 ...
 [ 14.2  85.1   5.8  87.9]
 [ 25.3  90.    5.3 100. ]
 [ 18.3  84.6   4.1 100. ]]
[15.0291269 84.711046   5.9852026 84.2838453]
[ 6.89942757  9.42413867  1.95641953 15.43296106]
[[ 0.50306682  1.15543228 -1.11693968  0.88227753]
 [-0.1491612  -0.49989141 -1.78141884 -0.02487179]
 [ 0.64800638  0.16860469 -0.35023296  1.01834992]
 ...
 [-0.12017329  0.0412721  -0.09466405  0.23431373]
 [ 1.48865583  0.56121352 -0.35023296  1.01834992]
 [ 0.47407891 -0.01178315 -0.96359833  1.01834992]]

In [97]:
top_scores = df[df['total_score'] > 90]
print(len(top_scores))

449426